spring:
  application:
    name: studing
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mongodb:
    uri: ${MONGODB_CONNECTION_STRING}
    auto-index-creation: false
  messages:
    basename: messages
    encoding: UTF-8
    use-code-as-default-message: true

jwt:
  secret: ${JWT_SECRET_BASE64}
